### ISSUE TITLE
Hardcoded paths in pubspec

### ISSUE THREAD

**Issue by bhariharan** [speaking-in-code/foostrainer3#1]
I can't build your project because of the hardcoded paths in a couple of places. Could you replace these with relative paths or URLs?

- `pubspec.lock`:

<img width="389" alt="pubspec 1" src="https://user-images.githubusercontent.com/1820287/85959836-b0ed7e80-b953-11ea-8e16-4852cf16a91d.png">

- `pubspec.yaml`:

<img width="602" alt="pubspec 2" src="https://user-images.githubusercontent.com/1820287/85959845-b945b980-b953-11ea-9924-b7df3584f7cc.png">

**Comment by speaking-in-code** [comment]
Just put in a fix.
